import Link from "next/link";
import { ArrowRight, Mail, MapPin, MessageCircle, Phone, Sparkles } from "lucide-react";
import { getLocale } from "@/lib/i18n";

const groups = {
  zh: [
    ["購買與付款", [["接受哪些付款方式？", "我們接受信用卡、Apple Pay、現金（只適用於門市自取）、PayMe、轉數快 FPS、AlipayHK 及 WeChat Pay HK；可用方式會在結帳頁顯示。"], ["訂單是否受保？", "每件作品均附 Iara 購買紀錄；可按產品頁列出的年期享保養及維修服務。"], ["配送是否需要簽收？", "香港配送一般需要收件人簽收，以確保珍貴作品安全送達。"], ["可以提供禮物訊息嗎？", "可以。結帳時可填寫禮物訊息，我們會以 Iara 包裝及卡片一併準備。"]]],
    ["產品與寶石", [["產品是天然鑽石還是培育鑽石？", "每件產品頁會清楚標示寶石資料及來源；如未有標示，歡迎聯絡珠寶顧問確認。"], ["是否附證書？", "有證書的作品會在產品規格標示；其他作品可按需要向團隊查詢證書資料。"], ["如何選擇戒指尺寸？", "可參考尺寸指南，或預約私人鑑賞讓顧問量度及比較佩戴比例。"], ["可以改尺寸或鏈長嗎？", "部分作品可提供尺寸調整或鏈長修改，時間及費用會按作品結構評估。"]]],
    ["配送、退換與售後", [["配送需要多久？", "香港現貨作品一般於 2 至 3 個工作天送達；訂製作品會按產品頁及確認電郵列出製作時間。"], ["可以退換嗎？", "未經刻字或訂製的作品可於收貨後 14 天內申請退換，作品須保持全新並連同完整包裝。"], ["保養及清潔服務包括甚麼？", "保養期內提供基本檢查及維修；我們亦提供清潔、拋光及尺寸評估服務。"], ["遺失單邊耳環可以補配嗎？", "我們會先確認款式及物料，再由工房評估能否補配及報價。"]]],
    ["Pet Atelier", [["寵物飾品可以每日佩戴嗎？", "Pet Atelier 作品以圓角及舒適比例設計，主要供裝飾及識別用途；請按寵物活動情況及扣件承重使用。"], ["可否連接牽引繩？", "除非產品頁明確標示，吊牌及吊飾不應連接牽引繩，亦不應作為承重扣件。"], ["刻字可以寫甚麼？", "可刻寵物名字及電話等簡短資料；字數、預覽及排版會按款式確認。"], ["有沒有防窒息設計？", "不同項目的扣件及承重設計不同，請在購買前向珠寶顧問確認，並避免讓寵物啃咬或誤吞寶石。"]]]
  ],
  en: [
    ["Buying and payment", [["Which payment methods do you accept?", "We accept credit card, Apple Pay, cash for atelier collection, PayMe, FPS, AlipayHK and WeChat Pay HK. Available methods are shown at checkout."], ["Are orders covered?", "Every piece is recorded in your Iara purchase history and covered by the care period shown on its product page."], ["Does delivery require a signature?", "Hong Kong deliveries generally require a signature to keep each piece secure."], ["Can I include a gift message?", "Yes. Add your message at checkout and we will prepare it with Iara packaging and a card."]]],
    ["Products and gemstones", [["Are the diamonds natural or lab-grown?", "Each product page identifies the stone information and origin where available. Contact a jewellery consultant if you need confirmation."], ["Is a certificate included?", "Pieces with certificates are identified in their specifications; our team can share certificate details on request."], ["How do I choose my ring size?", "Use our sizing guidance or book a private viewing so a consultant can measure and compare proportions."], ["Can I change the size or chain length?", "Selected pieces can be adjusted. Timing and pricing depend on the construction and will be confirmed by our team."]]],
    ["Delivery, returns and care", [["How long does delivery take?", "In-stock pieces usually arrive within 2 to 3 business days in Hong Kong. Made-to-order timing is confirmed by product and email."], ["Can I return or exchange a piece?", "Non-personalised pieces may be returned or exchanged within 14 days of delivery, in original condition with complete packaging."], ["What does care include?", "Basic inspection and repairs are included during the stated care period. Cleaning, polishing and sizing assessments are also available."], ["Can a single lost earring be remade?", "We will review the design and materials with our atelier before confirming feasibility and a quotation."]]],
    ["Pet Atelier", [["Can pet pieces be worn every day?", "Pet Atelier pieces are softly finished for decorative and identification use. Follow the product guidance and clasp load limits."], ["Can a tag connect to a lead?", "Unless a product explicitly says so, tags and charms should never be used as load-bearing lead attachments."], ["What can I engrave?", "Short names and phone numbers can be engraved on selected styles. Character limits and layout are confirmed before production."], ["Is there a breakaway safety design?", "Clasp and load designs vary by piece. Ask a consultant before purchase and prevent chewing or accidental ingestion."]]]
  ]
} as const;

export default async function FaqPage() {
  const en = await getLocale() === "en";
  const title = en ? "Frequently asked questions" : "常見問題與客戶服務";
  const intro = en ? "From stone selection and sizing to aftercare, the Iara team is here with considered guidance at every step." : "從選石、尺寸到售後保養，Iara 團隊會在每一步為你提供清晰而細緻的協助。";
  const faqGroups = en ? groups.en : groups.zh;
  return <main id="main" className="page-shell"><header className="page-heading container"><p className="eyebrow">CLIENT CARE</p><h1>{title}</h1><p>{intro}</p></header><section className="experience-band container"><div><Sparkles size={22} /><p className="eyebrow">THE IARA EXPERIENCE</p><h2>{en ? "A considered way to own jewellery" : "一套完整而細緻的 Iara 體驗"}</h2><p>{en ? "Signature packaging, complimentary Hong Kong delivery, 14-day returns, one-to-one guidance and ongoing cleaning checks." : "專屬包裝、香港免費配送、14 天退換、一對一珠寶顧問及持續清潔檢查服務。"}</p></div><Link className="text-link" href="/appointment">{en ? "Meet a jewellery consultant" : "預約珠寶顧問"}<ArrowRight size={14} /></Link></section><section className="faq-groups container">{faqGroups.map(([group, questions]) => <section className="faq-group" key={group}><h2>{group}</h2>{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>)}</section><section className="contact-band"><div><MapPin size={18} /><strong>{en ? "Iara Central Atelier" : "Iara 中環工作室"}</strong><span>香港中環皇后大道中 80 號</span></div><div><Phone size={18} /><strong>+852 2180 8208</strong><span>{en ? "Mon–Sun · 11:00–20:00" : "星期一至日 · 11:00–20:00"}</span></div><div><Mail size={18} /><strong>concierge@iara-jewellery.com</strong><span>{en ? "Client care" : "客戶服務"}</span></div><div><MessageCircle size={18} /><strong>WhatsApp</strong><span><a href="https://wa.me/85221808208" target="_blank" rel="noreferrer">{en ? "Message a consultant" : "聯絡珠寶顧問"}</a></span></div></section></main>;
}
