import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Package, UserRound } from "lucide-react";
import { db } from "@/lib/db";
import { requireStaff } from "@/lib/access";
import { formatDate, formatMoney } from "@/lib/format";
import { OpsPageHeader } from "@/components/ops-shell";
import { OrderDetailActions } from "@/components/ops-actions";
import { StatusPill } from "@/components/status-pill";

export default async function OpsOrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireStaff(); const { id } = await params;
  const order = await db.order.findUnique({ where: { id }, include: { items: true, payments: { orderBy: { createdAt: "desc" } }, history: { orderBy: { createdAt: "desc" }, take: 20 } } });
  if (!order) notFound();
  return <><OpsPageHeader eyebrow="COMMERCE / ORDER" title={order.orderNumber} description={`建立於 ${formatDate(order.createdAt)} · 最後更新 ${formatDate(order.updatedAt)}`} action={<Link className="button button-secondary" href="/ops/orders"><ArrowLeft size={15} />返回訂單</Link>} /><section className="order-detail-grid"><div className="ops-panel"><div className="order-detail-status"><div><span className="muted">訂單狀態</span><StatusPill value={order.orderStatus} /></div><div><span className="muted">付款狀態</span><StatusPill value={order.paymentStatus} /></div></div><OrderDetailActions id={order.id} orderStatus={order.orderStatus} paymentStatus={order.paymentStatus} /></div><div className="ops-panel"><div className="ops-panel-head"><div><h2><UserRound size={17} />客戶資料</h2></div></div><dl className="order-detail-list"><div><dt>姓名</dt><dd>{order.customerName}</dd></div><div><dt>電郵</dt><dd>{order.email}</dd></div><div><dt>電話</dt><dd>{order.phone}</dd></div><div><dt>配送方式</dt><dd>{order.deliveryMethod === "PICKUP" ? "門市自取" : "本地配送"}</dd></div><div><dt>地址</dt><dd>{order.shippingAddress || "未提供"}</dd></div>{order.giftMessage && <div><dt>禮物訊息</dt><dd>{order.giftMessage}</dd></div>}</dl></div><div className="ops-panel order-detail-items"><div className="ops-panel-head"><div><h2><Package size={17} />商品明細 <span className="muted">{order.items.length} 件</span></h2></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>商品</th><th>SKU</th><th>選項</th><th>數量</th><th>單價</th><th>小計</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td>{item.productName}</td><td>{item.sku}</td><td>{item.optionName}</td><td>{item.quantity}</td><td>{formatMoney(item.unitPriceMinor)}</td><td>{formatMoney(item.lineTotalMinor)}</td></tr>)}</tbody></table></div><div className="order-totals"><span>商品小計 <strong>{formatMoney(order.subtotalMinor)}</strong></span>{order.discountMinor > 0 && <span>折扣 <strong>-{formatMoney(order.discountMinor)}</strong></span>}<span>運費 <strong>{formatMoney(order.shippingMinor)}</strong></span><span className="total">訂單總額 <strong>{formatMoney(order.totalMinor)}</strong></span></div></div><div className="ops-panel"><div className="ops-panel-head"><div><h2>付款記錄</h2></div></div>{order.payments.length ? <div className="order-history-list">{order.payments.map((payment) => <div key={payment.id}><span>{payment.provider}</span><StatusPill value={payment.status} /><strong>{formatMoney(payment.amountMinor)}</strong><small>{formatDate(payment.createdAt)}</small></div>)}</div> : <p className="muted">尚未建立付款記錄。</p>}</div><div className="ops-panel"><div className="ops-panel-head"><div><h2>狀態歷程</h2></div></div>{order.history.length ? <div className="order-history-list">{order.history.map((entry) => <div key={entry.id}><StatusPill value={entry.status} /><span>{entry.note || "狀態更新"}</span><small>{formatDate(entry.createdAt)}</small></div>)}</div> : <p className="muted">尚未有狀態歷程。</p>}</div></section></>;
}
