"use client";
import { FormEvent, useState } from "react";
type Store = { id: string; name: string };
export function AppointmentForm({ stores }: { stores: Store[] }) {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const raw = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/appointments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...raw, marketingConsent: raw.marketingConsent === "on" }) }); const data = await response.json(); setMessage(response.ok ? `預約申請已收到，編號 ${data.appointment.id.slice(-8).toUpperCase()}。` : data.error); setBusy(false); if (response.ok) event.currentTarget.reset(); }
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0,10);
  return <form className="form-grid" onSubmit={submit}><div className="field"><label htmlFor="appointment-name">姓名</label><input id="appointment-name" name="name" required /></div><div className="field"><label htmlFor="appointment-phone">電話</label><input id="appointment-phone" name="phone" type="tel" required /></div><div className="field"><label htmlFor="appointment-email">電郵</label><input id="appointment-email" name="email" type="email" required /></div><div className="field"><label htmlFor="preferredContact">聯絡方式</label><select id="preferredContact" name="preferredContact"><option value="WHATSAPP">WhatsApp</option><option value="PHONE">電話</option><option value="EMAIL">電郵</option></select></div><div className="field"><label htmlFor="storeId">門市</label><select id="storeId" name="storeId">{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></div><div className="field"><label htmlFor="appointmentDate">日期</label><input id="appointmentDate" name="appointmentDate" type="date" min={tomorrow} required /></div><div className="field"><label htmlFor="timeSlot">時段</label><select id="timeSlot" name="timeSlot"><option>11:00</option><option>13:00</option><option>15:00</option><option>17:00</option><option>19:00</option></select></div><div className="field"><label htmlFor="interest">感興趣系列</label><select id="interest" name="interest"><option>LUMEA</option><option>ARIA</option><option>ARIA BRIDAL</option><option>MAREA</option><option>高級珠寶</option></select></div><div className="field full"><label htmlFor="budgetRange">預算範圍</label><select id="budgetRange" name="budgetRange"><option value="">尚未決定</option><option>HK$10,000 以下</option><option>HK$10,000–30,000</option><option>HK$30,000–60,000</option><option>HK$60,000 以上</option></select></div><div className="field full"><label htmlFor="notes">備註</label><textarea id="notes" name="notes" /></div><label className="checkbox-field field full"><input name="marketingConsent" type="checkbox" />我同意接收 Iara 品牌通訊（選填）。</label>{message && <p className={message.includes("已收到") ? "form-success field full" : "form-error field full"} role="status">{message}</p>}<button className="button button-primary field full" disabled={busy}>{busy ? "提交中…" : "提交預約"}</button></form>;
}
