"use client";
import { FormEvent, useState } from "react";
import type { Locale } from "@/lib/i18n";
type Store = { id: string; name: string };
export function AppointmentForm({ stores, locale = "zh-HK" }: { stores: Store[]; locale?: Locale }) {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const en = locale === "en";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch("/api/appointments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...raw, marketingConsent: raw.marketingConsent === "on" }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? (en ? `Request received. Reference ${data.appointment.id.slice(-8).toUpperCase()}.` : `預約申請已收到，編號 ${data.appointment.id.slice(-8).toUpperCase()}。`) : data.error || (en ? "Unable to submit your request." : "暫時未能提交預約，請稍後再試。")); if (response.ok) event.currentTarget.reset(); } catch { setMessage(en ? "Unable to submit your request." : "網絡連線失敗，請稍後再試。"); } finally { setBusy(false); } }
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0,10);
  return <form className="form-grid" onSubmit={submit}><div className="field"><label htmlFor="appointment-name">{en ? "Name" : "姓名"}</label><input id="appointment-name" name="name" required /></div><div className="field"><label htmlFor="appointment-phone">{en ? "Phone" : "電話"}</label><input id="appointment-phone" name="phone" type="tel" required /></div><div className="field"><label htmlFor="appointment-email">{en ? "Email" : "電郵"}</label><input id="appointment-email" name="email" type="email" required /></div><div className="field"><label htmlFor="preferredContact">{en ? "Contact preference" : "聯絡方式"}</label><select id="preferredContact" name="preferredContact"><option value="WHATSAPP">WhatsApp</option><option value="PHONE">{en ? "Phone" : "電話"}</option><option value="EMAIL">{en ? "Email" : "電郵"}</option></select></div><div className="field"><label htmlFor="storeId">{en ? "Atelier" : "門市"}</label><select id="storeId" name="storeId">{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></div><div className="field"><label htmlFor="appointmentDate">{en ? "Date" : "日期"}</label><input id="appointmentDate" name="appointmentDate" type="date" min={tomorrow} required /></div><div className="field"><label htmlFor="timeSlot">{en ? "Time" : "時段"}</label><select id="timeSlot" name="timeSlot"><option>11:00</option><option>13:00</option><option>15:00</option><option>17:00</option><option>19:00</option></select></div><div className="field"><label htmlFor="interest">{en ? "Collection of interest" : "感興趣系列"}</label><select id="interest" name="interest"><option>LUMEA</option><option>ARIA</option><option>ARIA BRIDAL</option><option>MAREA</option><option>IARA PETS</option></select></div><div className="field full"><label htmlFor="budgetRange">{en ? "Budget" : "預算範圍"}</label><select id="budgetRange" name="budgetRange"><option value="">{en ? "Not decided" : "尚未決定"}</option><option>{en ? "Below HK$10,000" : "HK$10,000 以下"}</option><option>HK$10,000–30,000</option><option>HK$30,000–60,000</option><option>{en ? "Above HK$60,000" : "HK$60,000 以上"}</option></select></div><div className="field full"><label htmlFor="notes">{en ? "Notes" : "備註"}</label><textarea id="notes" name="notes" /></div><label className="checkbox-field field full"><input name="marketingConsent" type="checkbox" />{en ? "I agree to receive Iara communications (optional)." : "我同意接收 Iara 品牌通訊（選填）。"}</label>{message && <p className={message.includes("已收到") || message.includes("received") ? "form-success field full" : "form-error field full"} role="status">{message}</p>}<button className="button button-primary field full" disabled={busy}>{busy ? (en ? "Submitting…" : "提交中…") : (en ? "Request appointment" : "提交預約")}</button></form>;
}
