"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
export function CheckoutForm() {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [order, setOrder] = useState<{orderNumber:string;orderId:string}|null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify(raw) }); const data = await response.json(); if (response.ok) { setOrder(data); setMessage(data.message || "請在安全付款元件完成付款。" ); } else setMessage(data.error); setBusy(false); }
  if (order) return <div className="empty-state"><h2>訂單 {order.orderNumber} 已建立</h2><p>{message}</p><Link className="button button-primary" href={`/order-confirmation/${order.orderId}`}>查看訂單狀態</Link></div>;
  return <form className="form-grid" onSubmit={submit}><div className="field"><label htmlFor="customerName">姓名</label><input id="customerName" name="customerName" required /></div><div className="field"><label htmlFor="checkout-phone">電話</label><input id="checkout-phone" name="phone" required /></div><div className="field full"><label htmlFor="checkout-email">電郵</label><input id="checkout-email" name="email" type="email" required /></div><div className="field full"><label htmlFor="deliveryMethod">取貨方式</label><select id="deliveryMethod" name="deliveryMethod"><option value="DELIVERY">香港配送</option><option value="PICKUP">中環門市自取</option></select></div><div className="field full"><label htmlFor="shippingAddress">配送地址</label><textarea id="shippingAddress" name="shippingAddress" /></div><div className="field"><label htmlFor="promotionCode">優惠碼</label><input id="promotionCode" name="promotionCode" placeholder="WELCOME10" /></div><div className="field"><label htmlFor="giftMessage">禮物訊息</label><input id="giftMessage" name="giftMessage" /></div>{message && <p className="form-error field full">{message}</p>}<button className="button button-primary field full" disabled={busy}>{busy ? "驗證價格及庫存…" : "建立安全付款"}</button><p className="muted field full" style={{fontSize:9}}>送出後系統會重新驗證價格、優惠與庫存。付款成功只以 Stripe 簽名 webhook 為準。</p></form>;
}
