"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { Banknote, CreditCard, Smartphone } from "lucide-react";
import type { Locale } from "@/lib/i18n";
type PaymentMethod = { code: string; nameZh: string; nameEn: string; instructionsZh: string | null; instructionsEn: string | null };
export function CheckoutForm({ methods, locale = "zh-HK" }: { methods: PaymentMethod[]; locale?: Locale }) {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [order, setOrder] = useState<{orderNumber:string;orderId:string}|null>(null);
  const en = locale === "en";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify(raw) }); const data = await response.json(); if (response.ok) { setOrder(data); setMessage(data.message || (en ? "Complete payment in the secure payment form." : "請在安全付款元件完成付款。") ); } else setMessage(en ? "We could not create your order. Check the delivery and payment details, then try again." : data.error); setBusy(false); }
  if (order) return <div className="empty-state"><h2>{en ? `Order ${order.orderNumber} created` : `訂單 ${order.orderNumber} 已建立`}</h2><p>{message}</p><Link className="button button-primary" href={`/order-confirmation/${order.orderId}`}>{en ? "View order status" : "查看訂單狀態"}</Link></div>;
  return <form className="form-grid" onSubmit={submit}><div className="field"><label htmlFor="customerName">{en ? "Name" : "姓名"}</label><input id="customerName" name="customerName" required /></div><div className="field"><label htmlFor="checkout-phone">{en ? "Phone" : "電話"}</label><input id="checkout-phone" name="phone" required /></div><div className="field full"><label htmlFor="checkout-email">{en ? "Email" : "電郵"}</label><input id="checkout-email" name="email" type="email" required /></div><div className="field full"><label htmlFor="deliveryMethod">{en ? "Delivery method" : "取貨方式"}</label><select id="deliveryMethod" name="deliveryMethod"><option value="DELIVERY">{en ? "Hong Kong delivery" : "香港配送"}</option><option value="PICKUP">{en ? "Collect from Central atelier" : "中環門市自取"}</option></select></div><div className="field full"><label htmlFor="shippingAddress">{en ? "Delivery address" : "配送地址"}</label><textarea id="shippingAddress" name="shippingAddress" /></div><fieldset className="checkout-payment full"><legend>{en ? "Payment method" : "付款方式"}</legend><div>{methods.map((method, index) => { const Icon = method.code === "CASH" ? Banknote : method.code === "CREDIT_CARD" ? CreditCard : Smartphone; return <label key={method.code}><input type="radio" name="paymentMethod" value={method.code} defaultChecked={index === 0} /><span><Icon size={18} /><strong>{en ? method.nameEn : method.nameZh}</strong><small>{en ? method.instructionsEn : method.instructionsZh}</small></span></label>; })}</div></fieldset><div className="field"><label htmlFor="promotionCode">{en ? "Promotion code" : "優惠碼"}</label><input id="promotionCode" name="promotionCode" placeholder="WELCOME10" /></div><div className="field"><label htmlFor="giftMessage">{en ? "Gift message" : "禮物訊息"}</label><input id="giftMessage" name="giftMessage" /></div>{message && <p className="form-error field full">{message}</p>}<button className="button button-primary field full" disabled={busy || !methods.length}>{busy ? (en ? "Verifying price and availability…" : "驗證價格及庫存…") : (en ? "Continue securely" : "建立安全付款")}</button><p className="muted field full" style={{fontSize:9}}>{en ? "Price, promotion and availability are verified again before the order is created. Online payment is confirmed only by a signed provider notification." : "送出後系統會重新驗證價格、優惠與庫存。網上付款成功只以供應商簽名通知為準。"}</p></form>;
}
