import Link from "next/link";
import { CalendarDays, ChevronRight, Crown, Gem, Gift, Heart, MapPin, Package, ShieldCheck, Sparkles, Star, UserRound } from "lucide-react";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/access";
import { formatDate, formatMoney } from "@/lib/format";
import { getLocale } from "@/lib/i18n";
import { StatusPill } from "@/components/status-pill";
import { ProductCard } from "@/components/product-card";
import { SignOutButton } from "@/components/sign-out-button";
import { AddressForm } from "@/components/address-form";
import { AccountSecurity } from "@/components/account-security";
import { MemberProfileForm } from "@/components/member-profile-form";

const tierTargets: Record<string, number> = { MEMBER: 500000, SILVER: 1500000, GOLD: 5000000, VIP: 10000000 };

export default async function AccountPage() {
  const [session, locale] = await Promise.all([requireUser(), getLocale()]);
  const en = locale === "en";
  const [user, orders, appointments, wishlist, pointRows] = await Promise.all([
    db.user.findUniqueOrThrow({ where: { id: session.user.id }, include: { addresses: { orderBy: { isDefault: "desc" } } } }),
    db.order.findMany({ where: { userId: session.user.id }, orderBy: { createdAt: "desc" }, include: { items: true } }),
    db.appointment.findMany({ where: { userId: session.user.id }, orderBy: { appointmentDate: "desc" }, include: { store: true } }),
    db.wishlistItem.findMany({ where: { userId: session.user.id }, include: { product: { include: { variants: { orderBy: { priceMinor: "asc" } } } } } }),
    db.pointsTransaction.findMany({ where: { userId: session.user.id }, orderBy: { createdAt: "desc" } })
  ]);
  const points = pointRows.reduce((sum, row) => sum + row.points, 0);
  const paidOrders = orders.filter((order) => order.paymentStatus === "PAID");
  const totalSpent = paidOrders.reduce((sum, order) => sum + order.totalMinor, 0);
  const nextTarget = tierTargets[user.membershipTier] || 10000000;
  const progress = Math.min(100, Math.round(totalSpent / nextTarget * 100));
  const nav = [["overview", en ? "Overview" : "會員總覽", UserRound], ["orders", en ? "Orders" : "訂單", Package], ["wishlist", en ? "Wishlist" : "願望清單", Heart], ["appointments", en ? "Appointments" : "預約", CalendarDays], ["addresses", en ? "Addresses" : "地址簿", MapPin], ["profile", en ? "Profile" : "個人資料", Star], ["privacy", en ? "Security" : "私隱及安全", ShieldCheck]] as const;
  return <main id="main" className="page-shell account-page"><section className="member-hero"><div className="container"><div><p className="eyebrow">IARA PRIVATE CLIENT</p><h1>{en ? `Welcome, ${user.name}` : `${user.name}，歡迎回來`}</h1><p>{en ? "Your jewellery, services and membership in one place." : "你的珠寶、服務與會員禮遇，集中於一處。"}</p></div><div className="member-tier-mark"><Crown size={20} /><span>{user.membershipTier}</span><small>{en ? "Member since" : "會員始於"} {new Intl.DateTimeFormat(en ? "en-HK" : "zh-HK", { year: "numeric", month: "short" }).format(user.createdAt)}</small></div></div></section><div className="account-layout container"><nav className="account-nav" aria-label={en ? "Member account" : "會員中心"}>{nav.map(([id, label, Icon]) => <a href={`#${id}`} key={id}><Icon size={15} />{label}</a>)}</nav><div className="account-main">
    <section id="overview" className="member-overview"><div className="member-summary"><div><p className="eyebrow">MEMBERSHIP STATUS</p><h2>{user.membershipTier} {en ? "Member" : "會員"}</h2><p>{en ? `${formatMoney(Math.max(0, nextTarget - totalSpent))} until your next recognition.` : `再累積 ${formatMoney(Math.max(0, nextTarget - totalSpent))} 即可達到下一個會員里程碑。`}</p><div className="member-progress"><span style={{ width: `${progress}%` }} /></div><small>{progress}%</small></div><Gem size={44} /></div><div className="member-stat-grid"><div><span>{en ? "Available points" : "可用積分"}</span><strong>{points.toLocaleString(en ? "en-HK" : "zh-HK")}</strong><small>{en ? "Use 1,000 points for HK$50" : "每 1,000 分可兌換 HK$50"}</small></div><div><span>{en ? "Orders" : "訂單"}</span><strong>{orders.length}</strong><small>{en ? `${paidOrders.length} completed payments` : `${paidOrders.length} 筆已完成付款`}</small></div><div><span>{en ? "Lifetime spend" : "累計消費"}</span><strong>{formatMoney(totalSpent)}</strong><small>{en ? "Eligible online and atelier purchases" : "合資格網上及門市消費"}</small></div></div></section>
    <section className="member-benefits"><div className="content-section-head"><div><p className="eyebrow">YOUR PRIVILEGES</p><h2>{en ? "Member privileges" : "你的會員禮遇"}</h2></div></div><div><article><Sparkles size={20} /><h3>{en ? "Private previews" : "新品優先鑑賞"}</h3><p>{en ? "Early access to new collections and limited pieces." : "優先預覽新系列及限量作品。"}</p></article><article><Gift size={20} /><h3>{en ? "Birthday gesture" : "生日禮遇"}</h3><p>{en ? "A considered Iara gesture during your birthday month." : "生日月份獲享 Iara 專屬心意。"}</p></article><article><Gem size={20} /><h3>{en ? "Care service" : "珠寶保養服務"}</h3><p>{en ? "Annual inspection and professional cleaning for selected pieces." : "指定作品享年度檢查與專業清潔。"}</p></article></div></section>
    <section className="content-section" id="orders"><div className="content-section-head"><div><p className="eyebrow">PURCHASE HISTORY</p><h2>{en ? "Your orders" : "訂單紀錄"}</h2></div><Link className="text-link" href="/shop">{en ? "Continue shopping" : "繼續選購"}</Link></div>{orders.length ? <div className="member-order-list">{orders.map((order) => <article key={order.id}><div><small>{formatDate(order.createdAt)}</small><strong>{order.orderNumber}</strong><span>{order.items.map((item) => item.productName).join(" · ")}</span></div><div><StatusPill value={order.orderStatus} /><strong>{formatMoney(order.totalMinor)}</strong><span>{order.paymentMethod.replaceAll("_", " ")}</span></div><ChevronRight size={17} /></article>)}</div> : <div className="empty-state"><h2>{en ? "No orders yet" : "尚未有訂單"}</h2><p>{en ? "Your Iara purchases will appear here." : "你的 Iara 選購紀錄會顯示在這裡。"}</p></div>}</section>
    <section className="content-section" id="wishlist"><div className="content-section-head"><div><p className="eyebrow">SAVED PIECES</p><h2>{en ? "Wishlist" : "願望清單"}</h2></div><span>{wishlist.length} {en ? "pieces" : "件作品"}</span></div>{wishlist.length ? <div className="product-grid">{wishlist.map(({ product }) => <ProductCard key={product.id} product={product} locale={locale} />)}</div> : <div className="empty-state"><Heart size={25} /><h2>{en ? "Save the pieces you love" : "收藏心儀作品"}</h2><p>{en ? "Select the heart on any piece to keep it here." : "點選作品上的心形圖示，即可在此慢慢比較。"}</p><Link className="button button-primary" href="/shop">{en ? "Explore jewellery" : "探索珠寶"}</Link></div>}</section>
    <section className="content-section" id="appointments"><div className="content-section-head"><div><p className="eyebrow">PRIVATE SERVICE</p><h2>{en ? "Appointments" : "預約紀錄"}</h2></div><Link className="text-link" href="/appointment">{en ? "Book an appointment" : "新增預約"}</Link></div>{appointments.length ? <div className="member-appointment-list">{appointments.map((item) => <article key={item.id}><CalendarDays size={19} /><div><strong>{formatDate(item.appointmentDate)} · {item.timeSlot}</strong><span>{item.store.name} · {item.interest}</span></div><StatusPill value={item.status} /></article>)}</div> : <div className="empty-state"><h2>{en ? "No appointments yet" : "尚未有預約"}</h2></div>}</section>
    <section className="content-section" id="addresses"><div className="content-section-head"><div><p className="eyebrow">DELIVERY</p><h2>{en ? "Address book" : "地址簿"}</h2></div></div><div className="address-grid">{user.addresses.map((address) => <article key={address.id}><MapPin size={18} /><div><strong>{address.label}{address.isDefault ? (en ? " · Default" : " · 預設") : ""}</strong><p>{address.recipient} · {address.phone}<br />{address.region}{address.district}{address.line1}</p></div></article>)}</div><details className="member-details"><summary className="button button-secondary">{en ? "Add address" : "新增地址"}</summary><div><AddressForm locale={locale} /></div></details></section>
    <section className="content-section" id="profile"><div className="content-section-head"><div><p className="eyebrow">PREFERENCES</p><h2>{en ? "Profile and preferences" : "個人資料與偏好"}</h2></div></div><MemberProfileForm initial={{ name: user.name, phone: user.phone, locale: user.locale, marketingConsent: user.marketingConsent }} locale={locale} /></section>
    <section className="content-section" id="privacy"><div className="content-section-head"><div><p className="eyebrow">ACCOUNT PROTECTION</p><h2>{en ? "Privacy and security" : "私隱及安全"}</h2></div></div><AccountSecurity twoFactorEnabled={user.twoFactorEnabled} deletionRequested={user.status === "DELETION_REQUESTED"} locale={locale} /><div className="account-signout"><SignOutButton locale={locale} /></div></section>
  </div></div></main>;
}
